channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - accelerate=0.29.2
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - antlr-python-runtime=4.9.3
  - appdirs=1.4.4
  - async-timeout=4.0.3
  - attrs=23.2.0
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.13
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.5
  - aws-c-mqtt=0.10.2
  - aws-c-s3=0.5.2
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.2
  - aws-sdk-cpp=1.11.267
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - cuda-cccl=11.8.89
  - cuda-command-line-tools=11.8.0
  - cuda-compiler=11.8.0
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cuobjdump=11.8.86
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=11.8.86
  - cuda-documentation=11.8.86
  - cuda-driver-dev=11.8.89
  - cuda-gdb=11.8.86
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.8.89
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.8.86
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.8.86
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-nvvp=11.8.87
  - cuda-profiler-api=11.8.86
  - cuda-runtime=11.8.0
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.8.0
  - cuda-tools=11.8.0
  - cuda-version=11.8
  - cuda-visual-tools=11.8.0
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - datasets=2.18.0
  - dill=0.3.8
  - docker-pycreds=0.4.0
  - filelock=3.13.4
  - frozenlist=1.4.1
  - fsspec=2024.2.0
  - gds-tools=1.4.0.31
  - gflags=2.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.7.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - hjson-py=3.1.0
  - huggingface_hub=0.22.2
  - icu=73.2
  - idna=3.6
  - impi_rt=2021.12.0
  - jinja2=3.1.3
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - libabseil=20230802.1
  - libaio=0.3.113
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcurl=8.7.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.17.0
  - libgoogle-cloud-storage=2.17.0
  - libgrpc=1.60.1
  - libhwloc=2.10.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm16=16.0.6
  - libmagma=2.7.2
  - libmagma_sparse=2.7.2
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libopenblas=0.3.27
  - libparquet=15.0.0
  - libprotobuf=4.25.1
  - libre2-11=2023.09.01
  - libsentencepiece=0.1.99
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtorch=2.1.2
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libxcrypt=4.4.36
  - libxml2=2.12.6
  - libzlib=1.2.13
  - llvm-openmp=18.1.3
  - lz4-c=1.9.4
  - magma=2.7.2
  - markupsafe=2.1.5
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=3.1.6
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.16
  - nccl=2.21.5.1
  - ncurses=6.4.20240210
  - networkx=3.3
  - nsight-compute=2022.3.0.22
  - numpy=1.26.4
  - omegaconf=2.3.0
  - openssl=3.2.1
  - orc=1.9.2
  - packaging=24.0
  - pandas=2.2.2
  - pathtools=0.1.2
  - pip=24.0
  - protobuf=4.25.1
  - psutil=5.9.8
  - py-cpuinfo=9.0.0
  - pyarrow=15.0.0
  - pyarrow-hotfix=0.6
  - pydantic=2.7.0
  - pydantic-core=2.18.1
  - pynvml=11.5.0
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.10
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - pytz=2024.1
  - pyyaml=6.0.1
  - rdma-core=51.0
  - re2=2023.09.01
  - readline=8.2
  - regex=2023.12.25
  - requests=2.31.0
  - s2n=1.4.5
  - safetensors=0.4.3
  - sentencepiece=0.1.99
  - sentencepiece-python=0.1.99
  - sentencepiece-spm=0.1.99
  - sentry-sdk=1.45.0
  - setproctitle=1.3.3
  - setuptools=69.5.1
  - six=1.16.0
  - sleef=3.5.1
  - smmap=5.0.0
  - snappy=1.1.10
  - sympy=1.12
  - tbb=2021.12.0
  - tk=8.6.13
  - tokenizers=0.15.2
  - tqdm=4.66.2
  - transformers=4.39.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucx=1.15.0
  - urllib3=2.2.1
  - wandb=0.16.5
  - wheel=0.43.0
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zstd=1.5.5
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - asyncio==3.4.3
    - cmake==3.29.2
    - deepspeed-kernels==0.0.1.dev1698255861
    - einops==0.7.0
    - ninja==1.11.1.1
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-nccl-cu11==2.19.3
    - nvidia-nvtx-cu11==11.8.86
    - pillow==10.2.0
    - torch==2.2.2+cu118
    - torchaudio==2.2.2+cu118
    - torchvision==0.17.2+cu118
    - triton==2.2.0
