model_type: llama
num_experts_per_tok: 2
base_model: team-sanai/llama2_7B_pretrain
virtual_expert: true
experts:
  - expert_name: "adapter_1"
    model_id: team-sanai/lama2_7B_lora_r720_sample
  - expert_name: "adapter_2"
    model_id: team-sanai/lama2_7B_lora_r720_sample
  - expert_name: "adapter_3"
    model_id: team-sanai/lama2_7B_lora_r720_sample