model_type: llama
num_experts_per_tok: 2
base_model: team-sanai/llama2_0.1B_seed
virtual_expert: true
experts:
  - expert_name: "adapter_1"
    model_id: team-sanai/llama2_0.1B_lora_sample_not_head
  - expert_name: "adapter_2"
    model_id: team-sanai/llama2_0.1B_lora_sample_not_head
  - expert_name: "adapter_3"
    model_id: team-sanai/llama2_0.1B_lora_sample_not_head