model_type: llama
num_experts_per_tok: 2
base_model: team-sanai/llama2_7B_pretrain_2nd
tokenizer: team-sanai/llama2_7B_pretrain_2nd
experts:
  - expert_name: "adapter_1"
    model_id: team-sanai/zoo_math_expert_epoch_1_v2
  - expert_name: "adapter_2"
    model_id: team-sanai/zoo_wiki_expert_epoch_1_v2
  - expert_name: "adapter_3"
    model_id: team-sanai/zoo_novel_expert_epoch_1_v2
